baseURL = "https://blog.0x77.page"
languageCode = "ru-ru"
title = "0x77dev blog"
theme = "terminal"
defaultContentLanguage = "ru"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme true default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Последнее обновление"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  oneHeadingSize = true

[params.twitter]
  creator = "Mikhail Marynenko"
  site = "https://0x77.page"

[languages]
  [languages.ru]
    languageName = "Русский"
    title = "0x77dev blog"
    subtitle = "Mikhail Marynenko blog"
    owner = "Mikhail Marynenko <0x77dev@protonmail.com>"
    keywords = "blog, 0x77dev, IT, dev, developing, cybersecurity, nodejs, graphql, protocols, sdr"
    copyright = "Mikhail Marynenko"
    menuMore = "Показать больше"
    readMore = "Читать больше"
    readOtherPosts = "Другие посты"
    missingContentMessage = "страница не найдена..."
    missingBackButtonLabel = "Вернутся домой"

    [languages.ru.params.logo]
      logoText = "0x77dev blog"
      logoHomeLink = "/"

    [languages.ru.menu]
      [[languages.ru.menu.main]]
        identifier = "website"
        name = "Мой сайтик"
        url = "https://0x77.page"
      [[languages.ru.menu.main]]
        identifier = "runspace"
        name = "Любимчик среди моих проектов: Runspace"
        url = "https://runspace.0x77.page"
